# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

exercises = [
    'Deadlift',
    'Sumo Deadlift',
    'Romanian Deadlift',
    'Snatch Grip Deadlift',
    'Straight Leg Deadlift',
    'Clean',
    'Muscle Clean',
    'Power Clean',
    'Squat Clean',
    'Hang Clean',
    'Hang Muscle Clean',
    'Hang Power Clean',
    'Hang Squat Clean',
    'Shoulder to Overhead',
    'Shoulder Press',
    'Push Press',
    'Push Jerk',
    'Split Jerk',
    'Snatch',
    'Muscle Snatch',
    'Power Snatch',
    'Squat Snatch',
    'Hang Snatch',
    'Hang Muscle Snatch',
    'Hang Power Snatch',
    'Hang Squat Snatch',
    'Snatch Balance',
    'Front Squat',
    'Back Squat',
    'Overhead Squat',
    'Thruster',
    'Cluster',
    'Bench Press',
    'Incline Bench Press',
    'Decline Bench Press',
    'Bent Over Row',
    'Front-rack Forward Lunge',
    'Front-rack Reverse Lunge',
    'Overhead Forward Lunge',
    'Overhead Reverse Lunge',
    'Dumbbell Deadlift',
    'Dumbbell Clean',
    'Dumbbell Muscle Clean',
    'Dumbbell Power Clean',
    'Dumbbell Squat Clean',
    'Dumbbell Hang Clean',
    'Dumbbell Hang Muscle Clean',
    'Dumbbell Hang Power Clean',
    'Dumbbell Hang Squat Clean',
    'Dumbbell Shoulder to Overhead',
    'Dumbbell Shoulder Press',
    'Dumbbell Push Press',
    'Dumbbell Push Jerk',
    'Dumbbell Split Jerk',
    'Alternating Dumbbell Snatch',
    'Dumbbell Snatch',
    'Dumbbell Muscle Snatch',
    'Dumbbell Power Snatch',
    'Dumbbell Squat Snatch',
    'Dumbbell Hang Snatch',
    'Dumbbell Hang Muscle Snatch',
    'Dumbbell Hang Power Snatch',
    'Dumbbell Hang Squat Snatch',
    'Dumbbell Squat',
    'Dumbbell Front Squat',
    'Dumbbell Goblet Squat',
    'Dumbbell Overhead Squat',
    'Dumbbell Thruster',
    'Dumbbell Cluster',
    'Dumbbell Farmer Carry',
    'Dumbbell Bench Press',
    'Dumbbell Incline Bench Press',
    'Dumbbell Decline Bench Press',
    'Dumbbell Floor Press',
    'Dumbbell Bent Over Row',
    'Dumbbell Bent Over Reverse Fly',
    'Bent-Over Reverse Fly',
    'Dumbbell Bicep Curl',
    'Bicep Curl + Shoulder Press',
    'Dumbbell Walking Lunge',
    'Dumbbell Reverse Walking Lunge',
    'Dumbbell Front-Rack Walking Lunge',
    'Dumbbell Front-Rack Reverse Walking Lunge',
    'Dumbbell Front-Rack Forward Lunge',
    'Dumbbell Front-Rack Reverse Lunge',
    'Dumbbell Overhead Forward Lunge',
    'Dumbbell Overhead Reverse Lunge',
    "Devil's Press",
    'Single-Arm Dumbbell Deadlift',
    'Single-Arm Dumbbell Clean',
    'Single-Arm Dumbbell Muscle Clean',
    'Single-Arm Dumbbell Power Clean',
    'Single-Arm Dumbbell Squat Clean',
    'Single-Arm Dumbbell Hang Clean',
    'Single-Arm Dumbbell Hang Muscle Clean',
    'Single-Arm Dumbbell Hang Power Clean',
    'Single-Arm Dumbbell Hang Squat Clean',
    'Single-Arm Dumbbell Shoulder to Overhead',
    'Single-Arm Dumbbell Shoulder Press',
    'Single-Arm Dumbbell Push Press',
    'Single-Arm Dumbbell Push Jerk',
    'Single-Arm Dumbbell Split Jerk',
    'Single-Arm Dumbbell Snatch',
    'Single-Arm Dumbbell Muscle Snatch',
    'Single-Arm Dumbbell Power Snatch',
    'Single-Arm Dumbbell Squat Snatch',
    'Single-Arm Dumbbell Hang Snatch',
    'Single-Arm Dumbbell Hang Muscle Snatch',
    'Single-Arm Dumbbell Hang Power Snatch',
    'Single-Arm Dumbbell Hang Squat Snatch',
    'Single-Arm Dumbbell Squat',
    'Single-Arm Dumbbell Front Squat',
    'Single-Arm Dumbbell Goblet Squat',
    'Single-Arm Dumbbell Overhead Squat',
    'Single-Arm Dumbbell Thruster',
    'Single-Arm Dumbbell Cluster',
    'Single-Arm Dumbbell Farmer Carry',
    'Single-Arm Dumbbell Bench Press',
    'Single-Arm Dumbbell Incline Bench Press',
    'Single-Arm Dumbbell Decline Bench Press',
    'Single-Arm Dumbbell Floor Press',
    'Single-Arm Dumbbell Bent Over Row',
    'Single-Arm Dumbbell Walking Lunge',
    'Single-Arm Dumbbell Reverse Walking Lunge',
    'Single-Arm Dumbbell Front-Rack Walking Lunge',
    'Single-Arm Dumbbell Front-Rack Reverse Walking Lunge',
    'Single-Arm Dumbbell Front-Rack Forward Lunge',
    'Single-Arm Dumbbell Front-Rack Reverse Lunge',
    'Single-Arm Dumbbell Overhead Forward Lunge',
    'Single-Arm Dumbbell Overhead Reverse Lunge',
    'Weighted Static Lunge',
    'Dumbbell Turkish Get-Up',
    'Kettlebell Deadlift',
    'Straight Leg Kettlebell Deadlift',
    'Kettlebell Clean',
    'Kettlebell Hang Clean',
    'Kettlebell Shoulder to Overhead',
    'Kettlebell Shoulder Press',
    'Kettlebell Push Press',
    'Kettlebell Push Jerk',
    'Kettlebell Split Jerk',
    'Kettlebell Snatch',
    'Single-Arm Kettlebell Squat',
    'Single-Arm Kettlebell Front Squat',
    'Kettlebell Goblet Squat',
    'Single-Arm Kettlebell Overhead Squat',
    'Single-Arm Kettlebell Thruster',
    'Single-Arm Kettlebell Cluster',
    'Kettlebell Farmer Carry',
    'Single-Arm Kettlebell Bench Press',
    'Single-Arm Kettlebell Incline Bench Press',
    'Single-Arm Kettlebell Decline Bench Press',
    'Single-Arm Kettlebell Floor Press',
    'Single-Arm Kettlebell Bent Over Row',
    'Single-Arm Kettlebell Reverse Walking Lunge',
    'Single-Arm Kettlebell Front-Rack Walking Lunge',
    'Single-Arm Kettlebell Front-Rack Reverse Walking Lunge',
    'Single-Arm Kettlebell Front-Rack Forward Lunge',
    'Single-Arm Kettlebell Front-Rack Reverse Lunge',
    'Single-Arm Kettlebell Overhead Forward Lunge',
    'Single-Arm Kettlebell Overhead Reverse Lunge',
    'Dual-Kettlebell Deadlift',
    'Dual-Kettlebell Cleans',
    'Dual-Kettlebell Hang Clean',
    'Dual-Kettlebell Shoulder to Overhead',
    'Dual-Kettlebell Shoulder Press',
    'Dual-Kettlebell Push Press',
    'Dual-Kettlebell Push Jerk',
    'Dual-Kettlebell Split Jerk',
    'Dual-Kettlebell Snatch',
    'Dual-Kettlebell Hang Snatch',
    'Dual-Kettlebell Squat',
    'Dual-Kettlebell Front Squat',
    'Dual-Kettlebell Overhead Squat',
    'Dual-Kettlebell Thruster',
    'Dual-Kettlebell Cluster',
    'Dual-Kettlebell Farmer Carry',
    'Dual-Kettlebell Bench Press',
    'Dual-Kettlebell Incline Bench Press',
    'Dual-Kettlebell Decline Bench Press',
    'Dual-Kettlebell Floor Press',
    'Dual-Kettlebell Bent Over Row',
    'Dual-Kettlebell Walking Lunge',
    'Dual-Kettlebell Reverse Walking Lunge',
    'Dual-Kettlebell Front-Rack Walking Lunge',
    'Dual-Kettlebell Front-Rack Reverse Walking Lunge',
    'Dual-Kettlebell Front-Rack Forward Lunge',
    'Dual-Kettlebell Front-Rack Reverse Lunge',
    'Dual-Kettlebell Overhead Forward Lunge',
    'Dual-Kettlebell Overhead Reverse Lunge',
    'Kettlebell Turkish Get-Up',
    'Squat',
    'Air Squat',
    'Jump Squat',
    'Jumping Squat',
    'Split Squat',
    'Sumo Squat',
    'Double Bench Squat',
    'Tuck Jump',
    'Broad Jump',
    'Step Up',
    'Bench Step Up',
    'Box Step Up',
    'Box Step Up With Knee Raise',
    'Box Jump',
    'Box Jump Over',
    'Bench Jump',
    'Bench Hop',
    'Pistol',
    'Wall Ball',
    'Jumping Lunge',
    'Forward Lunge',
    'Reverse Lunge',
    'Walking Lunge',
    'Reverse Walking Lunge',
    'Rebound Lunge',
    'Ring Row',
    'Jumping Pull-up',
    'Pull-Up',
    'Chin-Up',
    'Chest-to-Bar Pull-Up',
    'Ring Pull-Up',
    'Bar Muscle-Up',
    'Ring Muscle-Up',
    'Strict Pull-Up',
    'Strict Chest-to-Bar Pull-Up',
    'Strict Ring Pull-Up',
    'Strict Bar Muscle-Up',
    'Strict Ring Muscle-Up',
    'Static Hang',
    'Static Bar L-Sit',
    'Static Bar Tuck Hold',
    'Push-Up',
    'Incline Push-Up',
    'Decline Push-Up',
    'Lay-Down Push Up',
    'Rope Climb',
    'Handstand Push-Up',
    'Strict Handstand Push-Up',
    'Ring Dips',
    'Tricep Dip',
    'Double-Pulse Tricep Dip',
    'Sit-Up',
    'Sit-Ups With Twist',
    'Tuck-Up',
    'Straight Leg Sit-Ups',
    'Raised Leg Sit-Ups',
    'Raised Leg Sit-Ups With Twist',
    'Leg Raises',
    'Leg Raises On Bench',
    'V-Up',
    'Toe Touches',
    'Ab bikes',
    'Scissor Kicks',
    'Knees-to-Elbows',
    'Toes-to-Bar',
    'Toes-to-Rings',
    'GHD Sit-Up',
    'Plank',
    'Side Plank',
    'Forearm Plank',
    'Forearm Side Plank',
    'Stationary Caterpillar Walk',
    'Commando',
    'Russian Twist',
    'Mountain Climber',
    'Jumping Jack',
    'X Jump',
    'Burpee',
    'Burpee Box Jump Over',
    'Run',
    'Shuttle Run',
    'Backward Run',
    'Swim',
    'Spin',
    'BikeErg',
    'Assault Bike',
    'Rowing',
    'SkiErg',
    'Single-Unders',
    'Double-Unders',
    'Triple-Unders',
    'Medicine ball squat & press'
]
    
exercises.each do |exercise|
    Exercise.create(name: exercise)
end

Routine.create(name: 'Running & Lifting', description: "A quick cardio and strength workout.")

RoutineExercise.create(routine_id: Routine.find_by(name: 'Running & Lifting').id, exercise_id: Exercise.find_by(name: 'Run').id, quantity: nil, weight: nil, distance: 3, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Running & Lifting').id, exercise_id: Exercise.find_by(name: 'Bench Press').id, quantity: 10, weight: 135, distance: nil, duration: nil)

Routine.create(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout', description: "For a 14-minute workout, complete the 1st four exercises as many times as you can in seven minutes. Once completed, have a 30-60 second break and repeat this process with the 2nd four exercises. For a 28-minute workout, complete both sets again! ")

RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'Straight Leg Deadlift').id, quantity: 15, weight: 20, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'Split Squat').id, quantity: 15, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'Rebound Lunge').id, quantity: 20, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'Bench Jump').id, quantity: 12, weight: nil, distance: nil, duration: nil)

RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'Bench Hop').id, quantity: 20, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'Weighted Static Lunge').id, quantity: 24, weight: 20, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'X Jump').id, quantity: 20, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 1 - Leg Workout').id, exercise_id: Exercise.find_by(name: 'Squat').id, quantity: 15, weight: nil, distance: nil, duration: nil)

Routine.create(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout', description: "For a 14-minute workout, complete the 1st four exercises as many times as you can in seven minutes. Once completed, have a 30-60 second break and repeat this process with the 2nd four exercises. For a 28-minute workout, complete both sets again! ")

RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Bent-Over Reverse Fly').id, quantity: 15, weight: 20, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Lay-Down Push Up').id, quantity: 15, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Bicep Curl + Shoulder Press').id, quantity: 15, weight: 20, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Stationary Caterpillar Walk').id, quantity: 15, weight: nil, distance: nil, duration: nil)

RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Incline Push-Up').id, quantity: 15, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Double-Pulse Tricep Dip').id, quantity: 15, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Commando').id, quantity: 24, weight: nil, distance: nil, duration: nil)
RoutineExercise.create(routine_id: Routine.find_by(name: 'Sweat With Kayla Summer Series - Week 2 - Arm Workout').id, exercise_id: Exercise.find_by(name: 'Mountain Climber').id, quantity: 40, weight: nil, distance: nil, duration: nil)
